import type { Metadata } from 'next';
import { getSnapshot } from '@/lib/data';
import { EventList } from '@/components/ui';

export const metadata: Metadata = { title: 'Risk alerts' };

const RULES = [
  ['Score', 'Overall score moves ≥ 3 points between runs (alert at ≥ 8).'],
  ['Liquidity', 'TVL moves ≥ 10% in 24h (alert at ≥ 25%), or ≥ 15% over 7 days (alert at ≥ 35%).'],
  ['Collateral', 'Utilisation crosses 80% (watch) or 90% (alert).'],
  ['Activity', 'Weekly transactions swing ≥ 40% vs the prior week; success rate below 85%.'],
  ['Transparency', 'A registered contract is not found on-chain (registry drift).'],
];

export default async function AlertsPage() {
  const { snapshot } = await getSnapshot();
  const names = Object.fromEntries(snapshot.protocols.map((p) => [p.slug, p.name]));
  const counts = { alert: 0, watch: 0, info: 0 };
  for (const e of snapshot.events) counts[e.severity]++;

  return (
    <div className="two-up" style={{ gridTemplateColumns: 'minmax(0, 2fr) minmax(280px, 1fr)' }}>
      <div className="card">
        <div className="card-head">
          <span className="k k-ink">Detected risk events · last 30 days</span>
          <span style={{ display: 'flex', gap: 6 }}>
            <span className="tag tag-alert">{counts.alert} alert</span>
            <span className="tag tag-watch">{counts.watch} watch</span>
            <span className="tag tag-info">{counts.info} info</span>
          </span>
        </div>
        <EventList events={snapshot.events} names={names} />
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        <div className="card">
          <span className="k k-ink">Detection rules</span>
          <div style={{ display: 'flex', flexDirection: 'column', fontSize: 12.5 }}>
            {RULES.map(([k, r]) => (
              <div key={k} style={{ display: 'grid', gridTemplateColumns: '92px 1fr', gap: 10, padding: '8px 0', borderTop: '1px solid var(--color-rule)' }}>
                <span className="tag tag-outline" style={{ alignSelf: 'start' }}>{k}</span>
                <span style={{ color: 'var(--color-neutral-700)' }}>{r}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="note-box">
          Events are generated by the scoring engine on every run and deduplicated per protocol, day and rule. Automated delivery (webhooks, e-mail) is coming soon; the feed is available now at <code>GET /v1/risk-alerts</code>.
        </div>
      </div>
    </div>
  );
}
